version: '3'
services:
  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-12-may-2020/group-projects/scorpio/luna_project:master
    volumes:
    - frontend:/frontend/build
    - static-files:/static-files
    - media-files:/backend/media-files
    env_file:
      - ./env/prod.env
    command: 'sh /scripts/run.sh'
    depends_on:
      - db

  db:
    image: postgres:11
    env_file:
      - ./env/prod.env
    volumes:
      - postgres_db:/var/lib/postgresql/data


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static-files:/static-files
      - media-files:/media-files
      - frontend:/frontend
      - /etc/letsencrypt/:/etc/letsencrypt/


volumes:
  postgres_db:
  static-files:
  media-files:
  frontend:


